Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -38,23 +38,25 @@ jobs:
           #  with:
           #    node-version: 20
 
-          env:
-            # This is where you will need to introduce the Snyk API token created with your Snyk account
-            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-          with:
-            command: monitor
+          #env:
+          #  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+          #with:
+          #  command: monitor
 
           # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
         - name: Snyk Code test
           #run: snyk code test --sarif > snyk-code.sarif || true
           #run: snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
-          run: snyk code test --sarif --json-file-output=snyk-code.sarif || true
+          #run: snyk code test --sarif --json-file-output=snyk-code.sarif || true
+          run: snyk code test --sarif --json-file-output=snyk-code.sarif 2> snyk-error.log || true
+          env:
+            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         
           #SAST debug
-        - name: Show Snyk Code errors
+        #- name: Show Snyk Code errors
           #run: cat snyk-error.log
-          if: always()
-          run: cat snyk-error.log || true
+        #  if: always()
+        #  run: cat snyk-error.log || true
   
           # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
           #- name: Snyk Open Source monitor
@@ -63,6 +65,8 @@ jobs:
           # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
         - name: Snyk IaC test and report
           run: snyk iac test --report || true
+          env:
+            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
           # Build the docker image for testing
         #- name: Build a Docker image
@@ -80,6 +84,7 @@ jobs:
           run: |
                if [ ! -s snyk-code.sarif ]; then
                echo "❌ Snyk SARIF file is missing or empty!"
+               cat snyk-error.log || echo "No error log"
                exit 1
                fi
     
