Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -47,12 +47,15 @@ jobs:
           # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
         - name: Snyk Code test
           #run: snyk code test --sarif > snyk-code.sarif || true
-          run: snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
+          #run: snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
+          run: snyk code test --sarif --json-file-output=snyk-code.sarif || true
         
           #SAST debug
         - name: Show Snyk Code errors
-          run: cat snyk-error.log
-
+          #run: cat snyk-error.log
+          if: always()
+          run: cat snyk-error.log || true
+  
           # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
           #- name: Snyk Open Source monitor
           # run: snyk monitor --all-projects
@@ -72,6 +75,14 @@ jobs:
         #- name: Snyk Container monitor
         #  run: snyk container monitor your/image-to-test --file=Dockerfile
 
+        # Check SARIF output exists
+        - name: Check if snyk-code.sarif exists and is not empty
+          run: |
+               if [ ! -s snyk-code.sarif ]; then
+               echo "❌ Snyk SARIF file is missing or empty!"
+               exit 1
+               fi
+    
           # Push the Snyk Code results into GitHub Code Scanning tab
         - name: Upload result to GitHub Code Scanning
           uses: github/codeql-action/upload-sarif@v3
