Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -1,21 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-# A sample workflow which sets up Snyk to analyze the full Snyk platform (Snyk Open Source, Snyk Code,
-# Snyk Container and Snyk Infrastructure as Code)
-# The setup installs the Snyk CLI - for more details on the possible commands
-# check https://docs.snyk.io/snyk-cli/cli-reference
-# The results of Snyk Code are then uploaded to GitHub Security Code Scanning
-#
-# In order to use the Snyk Action you will need to have a Snyk API token.
-# More details in https://github.com/snyk/actions#getting-your-snyk-token
-# or you can signup for free at https://snyk.io/login
-#
-# For more examples, including how to limit scans to only high-severity issues
-# and fail PR checks, see https://github.com/snyk/actions/
-
 name: Snyk Security
 
 on:
@@ -29,60 +11,72 @@ permissions:
 
 jobs:
   snyk:
-    permissions:
-      contents: read # for actions/checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up Snyk CLI to check for security issues
-        # Snyk can be used to break the build when it detects security issues.
-        # In this case we want to upload the SAST issues to GitHub Code Scanning
-        # uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
-        uses: snyk/actions/setup@master
+      runs-on: ubuntu-latest
+      permissions:
+        contents: read
+        security-events: write
+        actions: read
+      steps:
+        - uses: actions/checkout@master
 
-        # For Snyk Open Source you must first set up the development environment for your application's dependencies
-        # For example for Node
-        #- uses: actions/setup-node@v4
-        #  with:
-        #    node-version: 20
+        - name: Install pnpm
+          run: npm install -g pnpm
+          
+        - name: Install dependencies
+          run: pnpm install
 
-        env:
-          # This is where you will need to introduce the Snyk API token created with your Snyk account
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-
-        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-        # Use || true to not fail the pipeline
-      - name: Snyk Code test
-        #run: snyk code test --sarif > snyk-code.sarif || true
-        run: snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
+        - name: Setup environment file
+          run: cp .env.example .env
         
-        #SAST debug
-      - name: Show Snyk Code errors
-        run: cat snyk-error.log
+        - name: Set up Snyk CLI to check for security issues
+          # Snyk can be used to break the build when it detects security issues.
+          # In this case we want to upload the SAST issues to GitHub Code Scanning
+          # uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
+          uses: snyk/actions/node@master
 
-        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-        #- name: Snyk Open Source monitor
-        # run: snyk monitor --all-projects
+          # For Snyk Open Source you must first set up the development environment for your application's dependencies
+          # For example for Node
+          #- uses: actions/setup-node@v4
+          #  with:
+          #    node-version: 20
 
-        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
-        # Use || true to not fail the pipeline.
-      - name: Snyk IaC test and report
-        run: snyk iac test --report || true
+          env:
+            # This is where you will need to introduce the Snyk API token created with your Snyk account
+            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+          with:
+            command: monitor
 
-        # Build the docker image for testing
-      - name: Build a Docker image
-        #run: docker build -t your/image-to-test .
-        run: | 
+          # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+          # Use || true to not fail the pipeline
+        - name: Snyk Code test
+          #run: snyk code test --sarif > snyk-code.sarif || true
+          run: snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
+        
+          #SAST debug
+        - name: Show Snyk Code errors
+          run: cat snyk-error.log
+
+          # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+          #- name: Snyk Open Source monitor
+          # run: snyk monitor --all-projects
+
+          # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+          # Use || true to not fail the pipeline.
+        - name: Snyk IaC test and report
+          run: snyk iac test --report || true
+
+          # Build the docker image for testing
+        - name: Build a Docker image
+          #run: docker build -t your/image-to-test .
+          run: | 
               docker build --progress=plain -t your/image-to-test . > docker-build.log 2>&1 || (cat docker-build.log && exit 1)
     
-        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
-      - name: Snyk Container monitor
-        run: snyk container monitor your/image-to-test --file=Dockerfile
+          # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
+        - name: Snyk Container monitor
+          run: snyk container monitor your/image-to-test --file=Dockerfile
 
-        # Push the Snyk Code results into GitHub Code Scanning tab
-      - name: Upload result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: snyk-code.sarif
+          # Push the Snyk Code results into GitHub Code Scanning tab
+        - name: Upload result to GitHub Code Scanning
+          uses: github/codeql-action/upload-sarif@v3
+          with:
+            sarif_file: snyk-code.sarif
